Spring :
  application:
    name: pass-web

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: pass_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

